package autocode

type ApiGroup struct {
	// Code generated by github.com/nooncall/owls/go Begin; DO NOT EDIT.
	AutoCodeExampleApi
	// Code generated by github.com/nooncall/owls/go End; DO NOT EDIT.
}
