package autocode

type ServiceGroup struct {
	// Code generated by github.com/qingfeng777/owls/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	// Code generated by github.com/qingfeng777/owls/server End; DO NOT EDIT.
}
