package autocode

type ApiGroup struct {
	// Code generated by github.com/qingfeng777/owls/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	// Code generated by github.com/qingfeng777/owls/server End; DO NOT EDIT.
}
