package autocode

type RouterGroup struct {
	// Code generated by github.com/qingfeng777/owls/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	// Code generated by github.com/qingfeng777/owls/server End; DO NOT EDIT.
}
