autocode:
  transfer-restart: true
  root: /Users/mingbai/openS/owls
  server: /go
  server-api: /api/v1/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-request: /model/%s/request/
  server-router: /router/%s
  server-service: /service/%s
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
cors:
  mode: whitelist
  whitelist:
  - allow-origin: example1.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
  - allow-origin: example2.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
db-filter:
  log-level: debug
  log-dir: ./
  num-once-limit: 100
  exec-no-backup: false
  aes-key: l02mx893j3283445
  aes-iv: 08783ksu3k390dj3
  reviewers:
  - zhangdashu
  - wangdazhang
  read-need-auth: false
excel:
  dir: ./resource/excel/
jwt:
  buffer-time: 86400
  expires-time: 604800
  issuer: qmPlus
  signing-key: c533863c-0484-42c2-a932-88ac519888d7
local:
  path: uploads/file
login:
  model: registry
  ldap:
    host: ldap.pri.ibanyu.com
    port: 389
    base-dn: dc=ipalfish,dc=com
    use-sll: false
    bind-pwd: Ccjsj1200
    bind-dn: cn=Manager,dc=ipalfish,dc=com
  login-path: http://baidu.com
  token-secret: ipalfish-db-injection-c362ef0dce45bb48b8f400e34b74c37b
  token-effective-hour: 0
  init-password: aaaaaa
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gva
  username: root
  password: aaaaaa
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
pgsql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
system:
  env: public
  addr: 8778
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  iplimit-count: 15000
  iplimit-time: 3600
  showsql: false
zap:
  level: info
  format: console
  prefix: '[github.com/nooncall/owls/go]'
  director: log
  showLine: false
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
