package autocode

type RouterGroup struct {
	// Code generated by github.com/nooncall/owls/go Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	// Code generated by github.com/nooncall/owls/go End; DO NOT EDIT.
}
