package autocode

type ServiceGroup struct {
	// Code generated by github.com/nooncall/owls/go Begin; DO NOT EDIT.
	AutoCodeExampleService
	// Code generated by github.com/nooncall/owls/go End; DO NOT EDIT.
}
